version: '3'

services:

  broker-service:
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports: 
      - "8080:85"
    deploy:
      mode: replicated
      replicas: 1


  db:
    image: mysql:8.0
    # cap_add:
    #   - SYS_NICE

    deploy:
      mode: replicated
      replicas: 1
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

#   mongo:
#     image: 'mongo:4.2.17-bionic'
#     ports:
#       - "27017:27017"
#     restart: always
#     deploy:
#       mode: replicated
#       replicas: 1
#     environment:
#       MONGO_INITDB_DATABASE: logs
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password
#     volumes:
#       - ./db-data/mongo/:/data/db

#   # postgres: start Postgres, and ensure that data is stored to a mounted volume (I didnt install Postgresql in my laptop before)
#   postgres:
#     image: 'postgres:14.2'
#     ports:
#       - "5432:5432"
#     restart: always
#     deploy:
#       mode: replicated
#       replicas: 1
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: users
#     volumes:
#       - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  db:
    driver: local